### ISSUE TITLE
Feedback on invalid form data

### ISSUE THREAD

**Issue by LeontiBrechko** [COMP308-Emerging-Technologies-Group2/COMP308-Group2-Favourite-Movie-List#28]
**Problem:** After clicking on 'Login' or 'Create an Account' button with empty input fields, there is no feedback on invalid form data. 
**Solution:** Show alert with a meaningful message when a user tries to login or register a new account.

**Comment by aagavin** [comment]
I think your solution works. A simple alert saying `wrong username or password`.

For create can we use HTML5 form validation?

**Comment by LeontiBrechko** [comment]
We can just use an alert controller with a proper message in the first clause of 'if' statement instead of console.log():
```
if (!this.registerForm.valid) {
  console.log(this.registerForm.value);
} else {
  // register/login user
  ...
}
```

**Comment by aagavin** [comment]
ah yea that would work
