### ISSUE TITLE
Search throws exception when clearing search field

### ISSUE THREAD

**Issue by eddieysong** [COMP308-Emerging-Technologies-Group2/COMP308-Group2-Favourite-Movie-List#35]
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'toLowerCase' of undefined

**Comment by aagavin** [comment]
Hmm OK. I'll look into this now

**Comment by aagavin** [comment]
@eddieysong which search page is this on?

**Comment by eddieysong** [comment]
@aagavin it's in the search view for movies. Let me know if you can't recreate it.
