### ISSUE TITLE
App crashes sometimes when logging in 

### ISSUE THREAD

**Issue by eddieysong** [COMP308-Emerging-Technologies-Group2/COMP308-Group2-Favourite-Movie-List#40]
![bug1](https://cloud.githubusercontent.com/assets/10310939/24779361/e27604ba-1afd-11e7-9edb-b1559a26a3ec.png)

**Comment by eddieysong** [comment]
Might be because AuthData class hasn't received a response before its methods/properties were accessed?

**Comment by LeontiBrechko** [comment]
It seems to be because of data retrieved from the ibmd api or view lifecycle: some object is not instantiated or the main collection of movies data is null before the view is rendered.

**Comment by LeontiBrechko** [comment]
Got the similar exception. It was caused during the next workflow:
1. Searched for a movie
2. Added movie to favourites
3. Clicked log out button
![screen shot 2017-04-14 at 2 38 42 pm](https://cloud.githubusercontent.com/assets/13102006/25052561/83204614-2120-11e7-864c-68c5db18371e.png)

**Comment by aagavin** [comment]
Strange I can't seem to reproduce. It just goes to the login page.
