### ISSUE TITLE
Cannot access favourites

### ISSUE THREAD

**Issue by LeontiBrechko** [COMP308-Emerging-Technologies-Group2/COMP308-Group2-Favourite-Movie-List#60]
I have added movies to favourite, logged out, then logged in back, and, finally, I always getting this exception when trying to access my favourites page.
![screen shot 2017-04-14 at 2 39 29 pm](https://cloud.githubusercontent.com/assets/13102006/25052730/3fda82ba-2121-11e7-8a85-af48bc64bd42.png)

**Comment by LeontiBrechko** [comment]
This one seems to be caused by #40, if you do not refresh a browser

**Comment by aagavin** [comment]
I was able to reproduce these steps.

**Comment by LeontiBrechko** [comment]
Refer to #61 description as possible partial fix

**Comment by aagavin** [comment]
I think this closed.
